export const AUTH_CONST = {
    LOGIN_REQUEST: "LOGIN_USER_REQUEST",
    LOGIN_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_FAILURE: "LOGIN_USER_FAILURE",
}
export const USER_CONST = {
    USER_REQUEST: "USER_REQUEST",
    USER_SUCCESS: "USER_SUCCESS",
    USER_FAILURE: "USER_FAILURE",
}
export const USER_LOGOUT = {
    USER_LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
}